spring.application.name=mtf-backend

# -----------------------------------------
# datasource configuration with env fallback
# -----------------------------------------
spring.datasource.url=${APP_DB_URL:${APP_DB_URL_LOCAL}}
spring.datasource.username=${APP_DB_USER:${APP_DB_USER_LOCAL}}
spring.datasource.password=${APP_DB_PASSWORD:${APP_DB_PASSWORD_LOCAL}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
